export default {
  index: 'ホーム',
  start: {
    title: 'はじめに',
    type: 'menu',
    items: {
      'getting-started': { title: 'クイックスタート' },
      setup: { title: 'セットアップ' },
      wizard: { title: 'ウィザード (CLI)' },
      'onboarding-overview': { title: 'オンボーディング概要' },
      onboarding: { title: 'オンボーディング (macOS)' },
      openclaw: { title: 'パーソナルアシスタント設定' },
      bootstrapping: { title: 'エージェントブートストラップ' },
      'docs-directory': { title: 'ドキュメントディレクトリ' },
      hubs: { title: 'ドキュメントハブ' },
      lore: { title: 'OpenClaw の由来' },
      showcase: { title: 'ショーケース' },
    },
  },
  gateway: {
    title: 'ゲートウェイ',
    type: 'menu',
    items: {
      index: { title: 'ランブック' },
      configuration: { title: '設定' },
      'configuration-reference': { title: '設定リファレンス' },
      'configuration-examples': { title: '設定例' },
      authentication: { title: '認証' },
      'background-process': { title: 'バックグラウンド実行' },
      bonjour: { title: 'Bonjour ディスカバリー' },
      'bridge-protocol': { title: 'ブリッジプロトコル' },
      'cli-backends': { title: 'CLI バックエンド' },
      discovery: { title: 'ディスカバリーとトランスポート' },
      doctor: { title: 'Doctor' },
      'gateway-lock': { title: 'ゲートウェイロック' },
      health: { title: 'ヘルスチェック' },
      heartbeat: { title: 'ハートビート' },
      'local-models': { title: 'ローカルモデル' },
      logging: { title: 'ロギング' },
      'multiple-gateways': { title: 'マルチゲートウェイ' },
      'network-model': { title: 'ネットワークモデル' },
      'openai-http-api': { title: 'OpenAI Chat Completions' },
      pairing: { title: 'ペアリング' },
      protocol: { title: 'ゲートウェイプロトコル' },
      remote: { title: 'リモートアクセス' },
      'remote-gateway-readme': { title: 'リモートゲートウェイ設定' },
      'sandbox-vs-tool-policy-vs-elevated': { title: 'Sandbox vs Tool Policy' },
      sandboxing: { title: 'サンドボックス' },
      secrets: { title: 'シークレット管理' },
      'secrets-plan-contract': { title: 'シークレットプランコントラクト' },
      'security/index': { title: 'セキュリティ' },
      tailscale: { title: 'Tailscale' },
      'tools-invoke-http-api': { title: 'Tools Invoke API' },
      troubleshooting: { title: 'トラブルシューティング' },
      'trusted-proxy-auth': { title: 'Trusted Proxy Auth' },
    },
  },
  channels: {
    title: 'チャネル',
    type: 'menu',
    items: {
      index: { title: '概要' },
      'channel-routing': { title: 'チャネルルーティング' },
      'broadcast-groups': { title: 'ブロードキャストグループ' },
      'group-messages': { title: 'グループメッセージ' },
      groups: { title: 'グループ' },
      location: { title: '位置情報パース' },
      pairing: { title: 'ペアリング' },
      troubleshooting: { title: 'トラブルシューティング' },
      line: { title: 'LINE' },
      slack: { title: 'Slack' },
      discord: { title: 'Discord' },
      telegram: { title: 'Telegram' },
      whatsapp: { title: 'WhatsApp' },
      imessage: { title: 'iMessage' },
      signal: { title: 'Signal' },
      msteams: { title: 'Microsoft Teams' },
      googlechat: { title: 'Google Chat' },
      matrix: { title: 'Matrix' },
      mattermost: { title: 'Mattermost' },
      irc: { title: 'IRC' },
      nostr: { title: 'Nostr' },
      twitch: { title: 'Twitch' },
      feishu: { title: 'Feishu' },
      tlon: { title: 'Tlon' },
      bluebubbles: { title: 'BlueBubbles' },
      'nextcloud-talk': { title: 'Nextcloud Talk' },
      'synology-chat': { title: 'Synology Chat' },
      zalo: { title: 'Zalo' },
      zalouser: { title: 'Zalo Personal' },
    },
  },
  concepts: {
    title: 'コンセプト',
    type: 'menu',
    items: {
      agent: { title: 'エージェントランタイム' },
      'agent-loop': { title: 'エージェントループ' },
      'agent-workspace': { title: 'エージェントワークスペース' },
      architecture: { title: 'ゲートウェイアーキテクチャ' },
      compaction: { title: 'コンパクション' },
      context: { title: 'コンテキスト' },
      features: { title: '機能一覧' },
      'markdown-formatting': { title: 'Markdown フォーマット' },
      memory: { title: 'メモリ' },
      messages: { title: 'メッセージ' },
      'model-failover': { title: 'モデルフェイルオーバー' },
      'model-providers': { title: 'モデルプロバイダー' },
      models: { title: 'モデル CLI' },
      'multi-agent': { title: 'マルチエージェントルーティング' },
      oauth: { title: 'OAuth' },
      presence: { title: 'プレゼンス' },
      queue: { title: 'コマンドキュー' },
      retry: { title: 'リトライポリシー' },
      session: { title: 'セッション管理' },
      'session-pruning': { title: 'セッションプルーニング' },
      'session-tool': { title: 'セッションツール' },
      sessions: { title: 'セッション' },
      streaming: { title: 'ストリーミングとチャンキング' },
      'system-prompt': { title: 'システムプロンプト' },
      timezone: { title: 'タイムゾーン' },
      typebox: { title: 'TypeBox' },
      'typing-indicators': { title: 'タイピングインジケーター' },
      'usage-tracking': { title: '使用量トラッキング' },
    },
  },
  tools: {
    title: 'ツール',
    type: 'menu',
    items: {
      index: { title: '概要' },
      'acp-agents': { title: 'ACP エージェント' },
      'agent-send': { title: 'Agent Send' },
      'apply-patch': { title: 'apply_patch ツール' },
      browser: { title: 'ブラウザ' },
      'browser-linux-troubleshooting': { title: 'ブラウザ (Linux)' },
      'browser-login': { title: 'ブラウザログイン' },
      'chrome-extension': { title: 'Chrome 拡張機能' },
      clawhub: { title: 'ClawHub' },
      elevated: { title: 'Elevated モード' },
      exec: { title: 'Exec ツール' },
      'llm-task': { title: 'LLM タスク' },
      lobster: { title: 'Lobster' },
      'multi-agent-sandbox-tools': { title: 'マルチエージェントサンドボックス' },
      plugin: { title: 'プラグイン' },
      reactions: { title: 'リアクション' },
      skills: { title: 'スキル' },
      'skills-config': { title: 'スキル設定' },
      'slash-commands': { title: 'スラッシュコマンド' },
      subagents: { title: 'サブエージェント' },
      thinking: { title: 'Thinking レベル' },
      web: { title: 'Web ツール' },
    },
  },
  automation: {
    title: '自動化',
    type: 'menu',
    items: {
      'auth-monitoring': { title: '認証モニタリング' },
      'cron-jobs': { title: 'Cron ジョブ' },
      'cron-vs-heartbeat': { title: 'Cron vs Heartbeat' },
      'gmail-pubsub': { title: 'Gmail PubSub' },
      hooks: { title: 'フック' },
      poll: { title: 'ポーリング' },
      troubleshooting: { title: 'トラブルシューティング' },
      webhook: { title: 'Webhook' },
    },
  },
  cli: {
    title: 'CLI リファレンス',
    type: 'menu',
    items: {
      index: { title: 'コマンド一覧' },
      acp: { title: 'acp' },
      agent: { title: 'agent' },
      agents: { title: 'agents' },
      approvals: { title: 'approvals' },
      browser: { title: 'browser' },
      channels: { title: 'channels' },
      clawbot: { title: 'clawbot' },
      completion: { title: 'completion' },
      config: { title: 'config' },
      configure: { title: 'configure' },
      cron: { title: 'cron' },
      daemon: { title: 'daemon' },
      dashboard: { title: 'dashboard' },
      devices: { title: 'devices' },
      directory: { title: 'directory' },
      dns: { title: 'dns' },
      docs: { title: 'docs' },
      doctor: { title: 'doctor' },
      gateway: { title: 'gateway' },
      health: { title: 'health' },
      hooks: { title: 'hooks' },
      logs: { title: 'logs' },
      memory: { title: 'memory' },
      message: { title: 'message' },
      models: { title: 'models' },
      node: { title: 'node' },
      nodes: { title: 'nodes' },
      onboard: { title: 'onboard' },
      pairing: { title: 'pairing' },
      plugins: { title: 'plugins' },
      qr: { title: 'qr' },
      reset: { title: 'reset' },
      sandbox: { title: 'sandbox' },
      secrets: { title: 'secrets' },
      security: { title: 'security' },
      sessions: { title: 'sessions' },
      setup: { title: 'setup' },
      skills: { title: 'skills' },
      status: { title: 'status' },
      system: { title: 'system' },
      tui: { title: 'tui' },
      uninstall: { title: 'uninstall' },
      update: { title: 'update' },
      voicecall: { title: 'voicecall' },
      webhooks: { title: 'webhooks' },
    },
  },
  install: {
    title: 'インストール',
    type: 'menu',
    items: {
      index: { title: '概要' },
      docker: { title: 'Docker' },
      node: { title: 'Node.js' },
      nix: { title: 'Nix' },
      bun: { title: 'Bun (実験的)' },
      ansible: { title: 'Ansible' },
      podman: { title: 'Podman' },
      fly: { title: 'Fly.io' },
      gcp: { title: 'GCP' },
      hetzner: { title: 'Hetzner' },
      railway: { title: 'Railway' },
      render: { title: 'Render' },
      northflank: { title: 'Northflank' },
      'exe-dev': { title: 'exe.dev' },
      'macos-vm': { title: 'macOS VM' },
      installer: { title: 'インストーラー内部' },
      'development-channels': { title: '開発チャネル' },
      migrating: { title: '移行ガイド' },
      updating: { title: 'アップデート' },
      uninstall: { title: 'アンインストール' },
    },
  },
  platforms: {
    title: 'プラットフォーム',
    type: 'menu',
    items: {
      index: { title: '概要' },
      macos: { title: 'macOS アプリ' },
      'mac/bundled-gateway': { title: 'macOS ゲートウェイ' },
      'mac/canvas': { title: 'Canvas' },
      'mac/child-process': { title: 'ゲートウェイライフサイクル' },
      'mac/dev-setup': { title: 'macOS 開発セットアップ' },
      'mac/health': { title: 'ヘルスチェック' },
      'mac/icon': { title: 'メニューバーアイコン' },
      'mac/logging': { title: 'ロギング' },
      'mac/menu-bar': { title: 'メニューバー' },
      'mac/peekaboo': { title: 'Peekaboo Bridge' },
      'mac/permissions': { title: '権限' },
      'mac/release': { title: 'リリース' },
      'mac/remote': { title: 'リモートコントロール' },
      'mac/signing': { title: '署名' },
      'mac/skills': { title: 'スキル' },
      'mac/voice-overlay': { title: 'Voice Overlay' },
      'mac/voicewake': { title: 'Voice Wake' },
      'mac/webchat': { title: 'WebChat' },
      'mac/xpc': { title: 'macOS IPC' },
      android: { title: 'Android' },
      ios: { title: 'iOS' },
      linux: { title: 'Linux' },
      windows: { title: 'Windows (WSL2)' },
    },
  },
  nodes: {
    title: 'ノード',
    type: 'menu',
    items: {
      index: { title: '概要' },
      audio: { title: 'オーディオとボイスメモ' },
      camera: { title: 'カメラキャプチャ' },
      images: { title: '画像とメディア' },
      'location-command': { title: '位置情報コマンド' },
      talk: { title: 'Talk モード' },
      troubleshooting: { title: 'トラブルシューティング' },
      voicewake: { title: 'Voice Wake' },
    },
  },
  web: {
    title: 'Web UI',
    type: 'menu',
    items: {
      index: { title: '概要' },
      'control-ui': { title: 'Control UI' },
      dashboard: { title: 'ダッシュボード' },
      tui: { title: 'TUI' },
      webchat: { title: 'WebChat' },
    },
  },
  plugins: {
    title: 'プラグイン',
    type: 'menu',
    items: {
      community: { title: 'コミュニティプラグイン' },
      'voice-call': { title: 'Voice Call プラグイン' },
      zalouser: { title: 'Zalo Personal プラグイン' },
    },
  },
  providers: {
    title: 'モデルプロバイダー',
    type: 'menu',
    items: {
      index: { title: '概要' },
      models: { title: 'クイックスタート' },
      anthropic: { title: 'Anthropic' },
      openai: { title: 'OpenAI' },
      bedrock: { title: 'Amazon Bedrock' },
      openrouter: { title: 'OpenRouter' },
      litellm: { title: 'LiteLLM' },
      mistral: { title: 'Mistral' },
      moonshot: { title: 'Moonshot AI' },
      minimax: { title: 'MiniMax' },
      glm: { title: 'GLM Models' },
      qianfan: { title: 'Qianfan' },
      opencode: { title: 'OpenCode Zen' },
      synthetic: { title: 'Synthetic' },
      'vercel-ai-gateway': { title: 'Vercel AI Gateway' },
      zai: { title: 'Z.AI' },
    },
  },
  reference: {
    title: 'リファレンス',
    type: 'menu',
    items: {
      'AGENTS.default': { title: 'デフォルト AGENTS.md' },
      RELEASING: { title: 'リリースチェックリスト' },
      credits: { title: 'クレジット' },
      'device-models': { title: 'デバイスモデル DB' },
      'prompt-caching': { title: 'プロンプトキャッシング' },
      rpc: { title: 'RPC アダプター' },
      'session-management-compaction': { title: 'セッション管理詳解' },
      'templates/AGENTS': { title: 'AGENTS.md テンプレート' },
      'templates/BOOT': { title: 'BOOT.md テンプレート' },
      'templates/BOOTSTRAP': { title: 'BOOTSTRAP.md テンプレート' },
      'templates/HEARTBEAT': { title: 'HEARTBEAT.md テンプレート' },
      'templates/IDENTITY': { title: 'IDENTITY.md テンプレート' },
      'templates/SOUL': { title: 'SOUL.md テンプレート' },
      'templates/TOOLS': { title: 'TOOLS.md テンプレート' },
      'templates/USER': { title: 'USER.md テンプレート' },
      test: { title: 'テスト' },
      'token-use': { title: 'トークン使用量とコスト' },
      wizard: { title: 'オンボーディングウィザード' },
    },
  },
  help: {
    title: 'ヘルプ',
    type: 'menu',
    items: {
      index: { title: '概要' },
      debugging: { title: 'デバッグ' },
      environment: { title: '環境変数' },
      faq: { title: 'FAQ' },
      scripts: { title: 'スクリプト' },
      testing: { title: 'テスト' },
      troubleshooting: { title: 'トラブルシューティング' },
    },
  },
  security: {
    title: 'セキュリティ',
    type: 'menu',
    items: {
      'formal-verification': { title: '形式検証' },
    },
  },
  experiments: {
    title: '実験的機能',
    type: 'menu',
    items: {
      'onboarding-config-protocol': { title: 'オンボーディング設定プロトコル' },
      'proposals/model-config': { title: 'モデル設定探索' },
      'research/memory': { title: 'ワークスペースメモリ研究' },
    },
  },
  ci: {
    title: 'CI パイプライン',
    href: '/ci',
  },
}
